apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demoapp
  name: demoapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demoapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demoapp
    spec:
      containers:
      - image: buore/demoapp:1
        name: demoapp
        ports:
        - containerPort: 5000
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: demoapp-service
  labels:
    app: demoapp-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: demoapp