node {
   def app
   environment {
   DOCKERHUB_CREDENTIALS = credentials('dockerhub')
   }

    stage ('Clone repository') 
    {
        checkout scm
    }

    stage ('Image build') {
       sh 'docker images'
       sh 'docker build -t buore/demoapp   -f demoapp/Dockerfile  .'
       sh 'docker tag buore/demoapp:latest   buore/demoapp:${BUILD_NUMBER}'
       app = 'buore/demoapp:${BUILD_NUMBER}'
       sh 'docker images'
    }

    stage ('Image test') {
        sh 'echo "Tests passed"'
    }

    stage('Login') {
        sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
    }

    // stage('Push') {
    //     sh 'docker push buore/demoapp:${BUILD_NUMBER}'
    // }

    stage('Push image') {
        docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
            app.push("${env.BUILD_NUMBER}")
        }
    }

    // stage('Update manifest') {
    //     sh "cat demoapp-deployment.yaml"
    //     echo "Updating manifest"
    //     build job: 'updatemanifest', parameters: [string(name: 'DOCKERTAG', value: env.BUILD_NUMBER)]
    // }

}
