node {
    def app
   environment {
    DOCKERHUB_CREDENTIALS = credentials('dockerhub')
   }

    stage ('Clone repository') 
    {
        checkout scm
    }

    stage ('Image build') {
       sh 'docker build -t buore/demoapp:1.${env.BUILD_NUMBER}.0   -f demoapp/Dockerfile  .'
       
    stage ('Image test') {
        sh 'echo "Tests passed"'
    }

    stage('Login') {
      steps {
        sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
      }
    }
    stage('Push') {
      steps {
        sh 'docker push buore/demoapp:1.${env.BUILD_NUMBER}'
      }
    }

    stage('Update manifest') {
        sh "cat demoapp-deployment.yaml"
        echo "Updating manifest"
        build job: 'updatemanifest', parameters: [string(name: 'DOCKERTAG', value: env.BUILD_NUMBER)]
    }

}

}